name: Publish Docker Image
on:
    push:
     branches:
     - main 
    release:
     types: [published]
jobs:
   build:
     runs-on: alpine
     steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GHCR_PASSWORD }}  
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2 
        with:
            push: true
            file: ./Dockerfile  
                  
                
              

          

